const fs = require('fs');

fs.mkdirSync('src/pages/video', { recursive: true });

const lines = [];
lines.push('---');
lines.push("import BaseLayout from '../../layouts/BaseLayout.astro';");
lines.push("import SiteNav from '../../components/SiteNav.astro';");
lines.push("import SiteFooter from '../../components/SiteFooter.astro';");
lines.push("import videos from '../../../public/data/videos.json';");
lines.push('');
lines.push('export function getStaticPaths() {');
lines.push('  return videos.map(v => ({');
lines.push('    params: { slug: v.slug },');
lines.push('    props: { video: v },');
lines.push('  }));');
lines.push('}');
lines.push('');
lines.push('const { video } = Astro.props;');
lines.push('const ytMatch = video.embedUrl?.match(/[?&]v=([^&]+)/);');
lines.push('const ytId = video.youtubeId || (ytMatch ? ytMatch[1] : null);');
lines.push('const embedSrc = video.embedSrc || (ytId ? `https://www.youtube-nocookie.com/embed/${ytId}` : null);');
lines.push('const thumb = ytId ? `https://img.youtube.com/vi/${ytId}/hqdefault.jpg` : video.thumbnail;');
lines.push('const isYoutube = !!(ytId && video.videoType !== "webinar");');
lines.push('---');
lines.push('');
lines.push('<BaseLayout title={video.title + " - Mycelium"}>');
lines.push('  <SiteNav />');
lines.push('');
lines.push('  <article class="vd-page">');
lines.push('    <div class="vd-inner">');
lines.push('      <div class="vd-back">');
lines.push('        <a href="/videos" class="back-link">');
lines.push('          <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M10 3L5 8L10 13" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>');
lines.push('          All Videos');
lines.push('        </a>');
lines.push('      </div>');
lines.push('      <div class="vd-layout">');
lines.push('        <div class="vd-main">');
lines.push('          {isYoutube && embedSrc ? (');
lines.push('            <div class="vd-embed">');
lines.push('              <iframe src={embedSrc} title={video.title} frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>');
lines.push('            </div>');
lines.push('          ) : (');
lines.push('            <div class="vd-embed-fallback">');
lines.push('              {(thumb || video.thumbnail) && <img src={thumb || video.thumbnail} alt={video.title} />}');
lines.push('              {video.embedUrl && (');
lines.push('                <div class="vd-external">');
lines.push('                  <a href={video.embedUrl} target="_blank" rel="noopener" class="btn-watch-full">Watch Full Video</a>');
lines.push('                </div>');
lines.push('              )}');
lines.push('            </div>');
lines.push('          )}');
lines.push('          <div class="vd-meta">');
lines.push('            <p class="vd-author">{video.author}</p>');
lines.push('            <h1 class="vd-title">{video.title}</h1>');
lines.push('            {video.tags && video.tags.length > 0 && (');
lines.push('              <div class="vd-tags">');
lines.push('                {video.tags.map((tag: string) => <span class="vd-tag">{tag}</span>)}');
lines.push('              </div>');
lines.push('            )}');
lines.push('            {video.description && <p class="vd-desc">{video.description}</p>}');
lines.push('          </div>');
lines.push('        </div>');
lines.push('        <div class="vd-sidebar">');
lines.push('          <h3 class="sidebar-title">About this Video</h3>');
lines.push('          <div class="sidebar-info">');
lines.push('            {video.author && (<div class="si-row"><span class="si-label">Speaker</span><span class="si-value">{video.author}</span></div>)}');
lines.push('            {video.videoType && (<div class="si-row"><span class="si-label">Format</span><span class="si-value si-cap">{video.videoType}</span></div>)}');
lines.push('          </div>');
lines.push('          <div class="sidebar-links">');
lines.push('            {video.embedUrl && <a href={video.embedUrl} target="_blank" rel="noopener" class="btn-watch-full">Watch Full Video</a>}');
lines.push('            <a href="/videos" class="btn-all">Browse All Videos</a>');
lines.push('          </div>');
lines.push('        </div>');
lines.push('      </div>');
lines.push('    </div>');
lines.push('  </article>');
lines.push('');
lines.push('  <SiteFooter />');
lines.push('</BaseLayout>');
lines.push('');
lines.push('<style>');
lines.push('.vd-page { background: #fff; min-height: 60vh; padding: 48px 40px 80px; }');
lines.push('.vd-inner { max-width: 1100px; margin: 0 auto; }');
lines.push('.vd-back { margin-bottom: 32px; }');
lines.push('.back-link { display: inline-flex; align-items: center; gap: 6px; font-family: var(--font-inter); font-size: 0.875rem; color: #666; transition: color 0.15s; text-decoration: none; }');
lines.push('.back-link:hover { color: #2F4F2F; }');
lines.push('.vd-layout { display: grid; grid-template-columns: 1fr 280px; gap: 48px; align-items: flex-start; }');
lines.push('.vd-embed { position: relative; aspect-ratio: 16/9; background: #000; border-radius: 12px; overflow: hidden; }');
lines.push('.vd-embed iframe { position: absolute; inset: 0; width: 100%; height: 100%; border: none; }');
lines.push('.vd-embed-fallback { border-radius: 12px; overflow: hidden; background: #f0f0f0; }');
lines.push('.vd-embed-fallback img { width: 100%; aspect-ratio: 16/9; object-fit: cover; }');
lines.push('.vd-external { padding: 20px; text-align: center; background: #f9f9f9; }');
lines.push('.vd-meta { margin-top: 28px; }');
lines.push('.vd-author { font-family: var(--font-inter); font-size: 0.75rem; font-weight: 600; letter-spacing: 0.12em; text-transform: uppercase; color: #2F4F2F; margin-bottom: 8px; }');
lines.push('.vd-title { font-family: var(--font-lora); font-size: clamp(1.4rem, 2.5vw, 2rem); font-weight: 600; color: #242424; line-height: 1.3; margin-bottom: 16px; }');
lines.push('.vd-tags { display: flex; gap: 8px; flex-wrap: wrap; margin-bottom: 20px; }');
lines.push('.vd-tag { font-family: var(--font-inter); font-size: 0.72rem; background: #F7F7F5; color: #555; padding: 4px 12px; border-radius: 50px; }');
lines.push('.vd-desc { font-family: var(--font-outfit); font-size: 1rem; color: #555; line-height: 1.7; }');
lines.push('.vd-sidebar { position: sticky; top: 88px; }');
lines.push('.sidebar-title { font-family: var(--font-lora); font-size: 1.1rem; font-weight: 600; color: #242424; margin-bottom: 20px; padding-bottom: 12px; border-bottom: 1px solid #f0f0f0; }');
lines.push('.sidebar-info { display: flex; flex-direction: column; gap: 12px; margin-bottom: 24px; }');
lines.push('.si-row { display: flex; flex-direction: column; gap: 2px; }');
lines.push('.si-label { font-family: var(--font-inter); font-size: 0.68rem; font-weight: 700; letter-spacing: 0.1em; text-transform: uppercase; color: #999; }');
lines.push('.si-value { font-family: var(--font-inter); font-size: 0.9rem; color: #242424; }');
lines.push('.si-cap { text-transform: capitalize; }');
lines.push('.sidebar-links { display: flex; flex-direction: column; gap: 10px; }');
lines.push('.btn-watch-full { font-family: var(--font-inter); font-size: 0.875rem; font-weight: 500; background: #5A3A1C; color: #fff; padding: 10px 20px; border-radius: 50px; transition: background 0.2s; text-decoration: none; display: block; text-align: center; }');
lines.push('.btn-watch-full:hover { background: #947153; }');
lines.push('.btn-all { font-family: var(--font-inter); font-size: 0.875rem; font-weight: 500; color: #242424; border: 1px solid #ccc; padding: 10px 20px; border-radius: 50px; transition: border-color 0.2s; text-decoration: none; display: block; text-align: center; }');
lines.push('.btn-all:hover { border-color: #2F4F2F; color: #2F4F2F; }');
lines.push('@media (max-width: 900px) { .vd-layout { grid-template-columns: 1fr; } .vd-sidebar { position: static; } }');
lines.push('@media (max-width: 600px) { .vd-page { padding: 32px 20px 60px; } }');
lines.push('</style>');

const content = lines.join('\n');
fs.writeFileSync('src/pages/video/[slug].astro', content);
const check = fs.readFileSync('src/pages/video/[slug].astro', 'utf8');
console.log('Written. Lines:', check.split('\n').length);
